apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backseat-driver
resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - db-init.yaml
  - api.yaml
  - workers.yaml
  - ui.yaml
images:
  - name: ghcr.io/shoham-b/backseat-driver-api
    newTag: latest
  - name: ghcr.io/shoham-b/backseat-driver-cli
    newTag: latest
  - name: ghcr.io/shoham-b/backseat-driver-ingest-worker
    newTag: latest
  - name: ghcr.io/shoham-b/backseat-driver-caption-worker
    newTag: latest
